apiVersion: v1
kind: Pod
metadata:
  name: helloworld-app
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld-container
    image: rajeswarr/nodejs
    ports:
      - containerPort: 3000
