apiVersion: v1
kind: Service
metadata:
  name: myhelloworld-service
spec:
  selector:
    appname: helloworld
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  type: LoadBalancer



